package com.example.gamesinfo;

import java.util.ArrayList;
import java.util.List;

public class GameData {
    public static List<Data> data = new ArrayList<>();

    static {
        data.add(
                new Data(
                        R.drawable.a,
                        "Apex Legends",
                        "Apex Legends - bu Respawn Entertainment tomonidan ishlab chiqilgan va Electronic Arts tomonidan nashr etilgan bepul jangovar royale - qahramon otishma o'yini. U PlayStation 4 , Windows va Xbox One uchun 2019-yil fevral oyida, Nintendo Switch uchun 2021-yil, va PlayStation 5 va Xbox Series X/S uchun 2022-yil mart oyida chiqarilgan.Oʻyinning mobil versiyasi Apex Legends Mobile deb nomlangan sensorli ekranlar uchun moʻljallangan. 2022-yil may oyida Android va iOS tizimlarida chiqarildi. O'yinyuqorida aytib o'tilgan mobil platformalar bundan mustasno, kross-platforma o'ynashni qo'llab-quvvatlaydi.\n" +
                                "\n" +
                                "O'yindan oldin o'yinchilar ikki yoki uch o'yinchidan iborat guruhlarga bo'linadi va \"Afsonalar\" deb nomlanuvchi o'ziga xos qobiliyatlarga ega, oldindan ishlab chiqilgan belgilardan tanlaydi. O'yin ikkita o'yin rejimiga ega. \"Battle Royale\" da 20 tagacha uch kishilik otryad yoki 30 ta ikki kishilik duet orolga qo'nib, jangda boshqa barcha o'yinchilarni mag'lub etishga urinishdan oldin qurol va jihozlarni qidiradi. Oroldagi mavjud o'yin maydoni vaqt o'tishi bilan kichrayib, o'yinchilarni harakatni davom ettirishga majbur qiladi yoki o'yin maydonidan tashqarida bo'lib qoladi, bu esa halokatli bo'lishi mumkin. Yakuniy jamoa raundda g'alaba qozonadi. \"Arenalar\"da o'yinchilar uch o'yinchidan iborat jamoalarga aylanadilar va o'yin g'olibini aniqlash uchun bir qator raundlar davomida 3v3 jamoaviy o'lim o'yinida boshqa jamoaga qarshi kurashadilar. Jamoalar kamida 3 ochkoga ega bo'lsa va 2 ochko oldinda bo'lsa, g'alaba qozonadi.\n" +
                                "\n" +
                                "Apex Legends Respawn Entertainment kompaniyasining Titanfall seriyasi bilan bir xil ilmiy fantastika olamida o'rnatiladi , Titanfall seriyasidagi bir nechta qahramonlar kichik qahramonlar yoki o'ynash mumkin bo'lgan afsonalar sifatida paydo bo'ladi. O'yin ustida ish 2016 yil oxirida boshlangan, ammo loyiha ishga tushirilgunga qadar sir bo'lib qoldi. Oʻyinning 2019-yilda chiqarilishi ajablanarli boʻldi, chunki oʻsha paytgacha Respawn Entertainment studiyaning oldingi yirik oʻyini boʻlgan Titanfall franshizasining uchinchi qismi ustida ishlamoqda deb taxmin qilingan edi. Apex Legends odatda tanqidchilardan ijobiy sharhlarni oldi, ular uning o'yin jarayonini, progressiv tizimini va turli janrlardagi elementlarning uyg'unligini maqtashdi. Ba'zilar uni boshqa battle royale o'yinlariga munosib raqobatchi deb bilishgan. Apex Legends o'zining birinchi haftasi oxirida 25 million o'yinchidan oshib ketdi va birinchi oyda 50 million o'yinchi. 2021 yilning apreliga kelib, u taxminan 100 million o'yinchiga ega bo'lib, uni o'yinchilar soni bo'yicha barcha davrlardagi eng ko'p o'ynalgan video o'yinlardan biriga aylantirdi."
                )
        );
        data.add(
                new Data(
                        R.drawable.b,
                        "Suicide Squad: Kill the Justice League",
                        "O‘z joniga qasd qilish guruhi: Adliya ligasini o‘ldir - bu Rocksteady Studios tomonidan ishlab chiqilganva Warner Bros. Games tomonidan nashr etilgan 2024-yilda yaratilgan sarguzashtli jangovar o‘yin . DC Comics jamoasining \"Suicide Squad\" ga asoslangan holda , bu Batman: Arkham seriyasining spin-offi va Batman: Arkham Knight (2015) ning davomi. Arkham Knight voqealaridan besh yil o'tib, o'yinning hikoyasi to'rtta yovuz odam - Kapitan Bumerang , Deadshot , Xarli Quinn va King Sharkdan iborat bo'lib, ular Amanda Uoller tomonidan yig'ilibo'zga sayyoralik bosqinchi Brainiakni to'xtatish va a'zolarini o'ldirish uchun Metropolisga yuboriladi.uning ta'siri ostida qolgan Adolat Ligasi .\n" +
                                "\n" +
                                "O'z joniga qasd qilish guruhi: Adolat ligasini o'ldirish uchinchi shaxs nuqtai nazaridan taqdim etilgan va uning ochiq dunyo dizayni o'yinchilarga yakka tartibda yoki birgalikda Metropolisda erkin sayr qilish imkonini beradi . O'yin 2020 yil avgust oyida e'lon qilingan va 2022 yilda chiqarilishi rejalashtirilgan edi, biroq bir necha marta kechiktirildi. U 2024-yil 29-yanvarda boshlangan hashamatli nashr egalari uchun erta kirish davriga ega edi.\n" +
                                "\n" +
                                "Kill the Justice League 2024-yil 2-fevralda PlayStation 5 , Windows va Xbox Series X/S uchun chiqarildi. O‘yin tanqidchilardan turli xil baholarni oldi, ular uning hikoyasi va o‘yin jarayonini maqtashdi, lekin uning takrorlanishi va jonli xizmat elementlarini tanqid qilishdi. Ba'zi muxlislar Kevin Konroyning video o'yinidagi so'nggi rolidagi Betmen obrazini ham tanqid qilishdi . O'yin Warner Bros. Games kompaniyasining sotuv bo'yicha kutganlarini qondira olmadi.\n" +
                                "\n" +
                                "O'yin \n" +
                                "O'z joniga qasd qilish guruhi: Adliya ligasini o'ldir - bu Metropolisda joylashgan ochiq dunyoda o'rnatilgan sarguzashtli o'yin [2] . [3] O'yinda beshta o'ynash mumkin bo'lgan belgilar mavjud: Kapitan Bumerang , Deadshot , Xarli Quinn , Joker va King Shark . [ Iqtibos kerak ] Uni yakkaxon oʻynash mumkin boʻlsa-da, oʻyin toʻrt oʻyinchili kooperativ multiplayer rejimiga ega . Yakkaxon o'ynaganida, o'yinchilar o'z xohishlariga ko'ra personajlar o'rtasida almashishlari mumkin, qolgan belgilar esa AI tomonidan boshqariladi . [4] [5]\n" +
                                "\n" +
                                "Har bir belgi uchta qurol sinfiga kirish huquqiga ega, har bir sinf ishga tushirilganda mavjud bo'lgan to'rtta belgidan ikkitasi tomonidan baham ko'riladi. Har bir qahramon o'ziga xos jangovar jang uslubi va o'tish usuliga ega, masalan, Xarli Quinn, u kaltakni ishlatadi va Batmanning qurolidan foydalangan holda sayohat qiladi. O'yinchilarga o'yin davomida istalgan vaqtda turli xil tajribalar uchun turli ko'nikmalarni qayta ko'rib chiqishga imkon beruvchi mahorat daraxti progressiya tizimi kiritilgan. [6] Ishga tushirilgandan keyingi kontent “fasllar” koʻrinishida chiqariladi, yangi joylar, harakatlar va oʻynaladigan belgilar bilan tez-tez bepul kontent yangilanadi. [7]"
                )
        );
        data.add(
                new Data(
                        R.drawable.c,
                        "League of Legends",
                        "Liga of Legends ( LoL ), odatda Liga deb ataladi, Riot Games tomonidan ishlab chiqilgan va nashr etilgan 2009-yilda koʻp oʻyinchi onlayn jangovar arena video oʻyini . Warcraft III uchunmaxsus xarita boʻlgan Qadimgilar mudofaasidan ilhomlanganRiot asoschilari xuddi shu janrda mustaqil oʻyinni ishlab chiqishga intilishdi. 2009-yil oktabr oyida chiqarilganidan beri Liga oʻynash bepul va sotib olinadigan belgilarni sozlashorqali monetizatsiya qilinadiO'yin Microsoft Windows va macOS uchun mavjud .\n" +
                                "\n" +
                                "O'yinda besh o'yinchidan iborat ikkita jamoa o'yinchi va o'yinchi jangida kurashadi, har bir jamoa xaritaning yarmini egallab, himoya qiladi. O'n nafar o'yinchining har biri o'ziga xos qobiliyat va turli o'yin uslublariga ega \"chempion\" deb nomlanuvchi belgini boshqaradi. O'yin davomida chempionlar tajriba ochkolarini to'plash , oltin ishlab chiqarish va raqib jamoani mag'lub etish uchun narsalarni sotib olish orqali kuchliroq bo'lishadi . Liganing asosiy rejimi, Summoner's Riftda, jamoa dushman bazasiga borib, uning ichida joylashgan \"Nexus\" ni yo'q qilish orqali g'alaba qozonadi .\n" +
                                "\n" +
                                "Liga of Legends umuman ijobiy sharhlarni oldi; tanqidchilar uning qulayligi, xarakter dizaynlari va ishlab chiqarish qiymatini ta'kidladilar. O'yinning uzoq umr ko'rishi tanqidiy qayta baholashga olib keldi, sharhlar ijobiy tendentsiyaga ega; u yaratilgan eng buyuk video o'yinlardan biri hisoblanadi . Biroq, o'yinning dastlabki kunlaridan beri tanqid qilingan o'yinchining salbiy va haqoratli xatti-harakati, Riotning muammoni tuzatishga urinishlariga qaramay davom etmoqda. 2019-yilda Liga muntazam ravishda sakkiz million o‘yinchini qamrab oldi va uning mashhurligi musiqa, komikslar, qisqa hikoyalar va Arcane animatsion seriyasi kabi birlashmalarga olib keldi . Uning muvaffaqiyati bir nechta spin-off video o'yinlarini tug'dirdi , jumladan, League of Legends: Wild Rift , mobil versiyasi; Legends of Runeterra , raqamli yig'iladigan karta o'yini; va Ruined King: A League of Legends Story , navbatga asoslangan rolli o'yin va boshqalar . Mulk asosidagi ommaviy ko'p o'yinchi onlayn rolli o'yin ishlab chiqilmoqda.\n" +
                                "\n" +
                                "Afsonalar ligasi dunyodagi eng yirik sport turi bo'lib , xalqaro musobaqalar ko'plab mintaqaviy ligalardan iborat bo'lib, har yili o'tkaziladigan League of Legends Jahon chempionati bilan yakunlanadi . 2019-yilgi tadbir 100 milliondan ortiq noyob tomoshabinlarni ro‘yxatga oldi va final bosqichida bir vaqtning o‘zida 44 million tomoshabinni ko‘rsatdi . Mahalliy va xalqaro tadbirlar Twitch , YouTube , Bilibili va ESPN kabel televideniesi sport kanali kabi jonli efir veb- saytlarida translyatsiya qilingan ."
                )
        );
        data.add(
                new Data(
                        R.drawable.d,
                        "Call of Duty",
                        "Call of Duty , shuningdek, (COD) deb ataladi, 2003-yildan boshlab Activision tomonidan nashr etilgan video oʻyinlar seriyasi va media franchayzidir. Oʻyinlar dastlab Infinity Ward , keyin Treyarch va Sledgehammer Games tomonidan ishlab chiqilgan . Bir nechta spin-off va qo'lda o'yinlar boshqa ishlab chiquvchilar tomonidan yaratilgan. Eng so‘nggi nom, Call of Duty: Modern Warfare III 2023-yil 10-noyabrda chiqarilgan.\n" +
                                "\n" +
                                "Serial dastlab Ikkinchi Jahon urushi sahnasiga qaratilgan edi, Infinity Ward Call of Duty (2003) va Call of Duty 2 (2005) va Treyarch Call of Duty 3 (2006) ni ishlab chiqdi . Call of Duty 4: Modern Warfare (2007) zamonaviy sozlamani taqdim etdi va Modern Warfare kichik seriyasini yaratib, seriya uchun yutuq sarlavhasi ekanligini isbotladi ; a Modern Warfare remastered versiyasi 2016-yilda chiqarilgan. Ikki boshqa yozuvlar Modern Warfare 2 (2009) va Modern Warfare 3 (2011) qilingan. Kichik seriyalar 2019-yilda Modern Warfare , 2022-yilda Modern Warfare II va 2023-yilda Modern Warfare III bilan qayta ishga tushirildi. Infinity Ward shuningdek, Modern Warfare kichik seriyasidan tashqari ikkita oʻyinni ishlab chiqdi : Ghosts (2013) va Infinite Warfare ( 2016).\n" +
                                "\n" +
                                "Treyarch Black Ops ( 2010) ni chiqarishdan va keyinchalik Black Ops kichik seriyasini yaratishdan oldin Ikkinchi Jahon Urushiga asoslangan oxirgi o'yinni yaratdi, World at War (2008). Yana to'rtta yozuv, Black Ops II (2012), Black Ops III (2015), Black Ops 4 (2018) va Sovuq urush (2020), ikkinchisi Raven Software bilan birgalikda qilingan . Modern Warfare 3 uchun hammualliflar bo'lgan Sledgehammer Games, shuningdek, uchta nom ishlab chiqdi: Advanced Warfare (2014), Call of Duty: WWII (2017) va Vanguard (2021). Ular, shuningdek, Modern Warfare III (2023) ning bosh ishlab chiquvchisi bo‘lib , Modern Warfare reboot kichik seriyasining uchinchi qismidir .\n" +
                                "\n" +
                                "2021-yil aprel oyi holatiga ko‘ra , Call of Duty 400 million nusxadan ortiq sotilgan. [1] Bu seriya Ginnesning rekordlar kitobi tomonidan eng koʻp sotilgan birinchi shaxs otishma oʻyinlari seriyasi sifatida tasdiqlangan . Bu, shuningdek, Qo'shma Shtatlarda yaratilgan eng muvaffaqiyatli video o'yinlar franchayzi va barcha vaqtlardagi to'rtinchi eng ko'p sotilgan video o'yinlar franchayzidir . Franshizadagi boshqa mahsulotlar qatoriga Plan B Toys tomonidan ishlab chiqilgan aksiyalar figuralari qatori , Upper Deck kompaniyasi tomonidan yaratilgan karta o'yini , Mega Brands tomonidan yaratilgan Mega Bloks to'plamlari va WildStorm Productions tomonidan nashr etilgan mini- komikslar seriyasi va ishlab chiqilayotgan badiiy film kiradi."
                )
        );
        data.add(
                new Data(
                        R.drawable.e,
                        "Granblue Fantasy: Relink",
                        "Granblue Fantasy: Relink [c] - buCygamestomonidan ishlab chiqilgan va nashr etilganrolli o'yin.PlayStation 4,PlayStation 5vaWindowsuchun Granblue Fantasy franshizasining bir qismi sifatida chiqarildi. U tanqidchilarning ijobiy sharhlarini oldi va chiqarilgandan keyin ikki hafta ichida million nusxada yuborildi.\n" +
                                "\n" +
                                "Syujet \n" +
                                "Kapitan va ularning Liriya, Vyrn, Katalina, Io, Rackam, Eugen va Rosettadan iborat bo'lgan ekipaji afsonaviy Estaluciya astral shohligini topish uchun sayohati davomida o'zlarining dirijabllari bo'lgan Grandcypher bortida Zegagrande osmoniga yetib kelishadi . Ularga yetib kelganidan ko‘p o‘tmay, yirtqich hayvonlar hujum qiladi va kapitan va Liriyani ularni qaytarish uchun asosiy ajdaho Bahamutni chaqirishga majbur qiladi. Biroq, Liria to'satdan Bahamut ustidan nazoratni yo'qotadi va u kemaga hujum qila boshlaydi, ekipaj uni zo'rg'a bo'ysundira oladi. Liriya Bahamutni nazorat ostiga olish qiyinligi tufayli dengizga yiqilib tushadi, kapitan va Vrin ham uni qutqarish uchun dengizdan chiqib ketadi. Ularni erdagi ekipajning qolgan a'zolari qutqaradi va ular eng yaqin Folka qishlog'iga yo'l olishadi. Grandcypher ta'mirdan o'tayotganda, ekipaj qishloqning mahalliy ruhoniysi va o'zini usta deb e'lon qilgan Rolan bilan uchrashadi .\n" +
                                "\n" +
                                "Kapitan Rolanga yaqin atrofdagi Tempeal orolidan qishloq aholisini evakuatsiya qilishda yordam berishga qaror qiladi, chunki u erdagi asosiy hayvon Furycane halokatli shamol bo'ronlarini keltirib chiqaradi. Ekipaj Furycane ziyoratgohini bosib olish uchun borishdan oldin barcha qishloq aholisini qutqaradi. Ular Furycaneni muvaffaqiyatli bo'ysundirar ekan, ular Lilit boshchiligidagi Avia cherkovi tomonidan pistirmaga duchor bo'lishadi, u Estalusiyaga borish rejasining bir qismi sifatida Liriyani qo'lga kiritadi. Ekipaj uni to'xtatishga harakat qiladi, faqat uning tansoqchisi Id tomonidan mag'lub bo'ladi. Ekipaj qayta to'planish uchun Folkaga chekinishga majbur bo'ladi, u erda Rolan ularga yordam berishga rozi bo'ladi. Ular Lilit va Liriyani yangi ta'mirlangan Grandcypher bilan Managarmr ziyoratgohigacha ta'qib qiladilar va u erda Lilit maxsus yoqa orqali Liriyani o'z nazoratiga olganligini aniqlaydilar. Ular Liriyaning Managarmrni o'ziga singdirib, yana qochib ketishini to'xtata olmaydilar. Keyin Rolan ekipajni Zegagrande Skydomning poytaxti Seedhollow shahriga olib boradi, u aqlni boshqarish bo'yinbog'ini qanday olib tashlashni biladigan yer osti dunyosi ma'lumotchisi Zathba bilan maslahatlashadi. Zathba ekipajni yaqin atrofdagi vayronalarga jo'natadi, ularda yoqani o'chirish uchun qurilma mavjud va ular tiklanadi. Ekipaj yana bir bor Lilitni asosiy hayvon Vulkan Bolla ziyoratgohi tomon quvib yetib boradi va u erda qisqa vaqt ichida Id bilan birga Liriyani asl hayvondan qutqaradi. Biroq, Liliyadan yoqani yechib olishlariga qaramay, ular Lilitning yana u bilan qochib ketishini to'xtata olishmaydi.\n" +
                                "\n" +
                                "Vaziyat og'ir ekanini ko'rib, Rolan nihoyat ekipajga o'zi ham, Lilit ham osmon shohligida qolib ketgan Astral ekanligini ochib beradi. Rolan odamlar orasida yashashdan mamnun bo'lsa-da, Lilit uyiga Estalusiyaga qaytishni orzu qilib, uni Avia cherkovini ochishga olib keldi. Uning rejasiga ko'ra, Angra Mainyuning asosiy hayvonini jonlantirish va keyin Liriya unga singib ketgan asosiy hayvonlarni qurbon qilish, bu esa unga Estlaucia portalini ochish imkoniyatini beradi. Biroq, Rolan bunday harakat osmon shohligini butunlay yo'q qilishi haqida ogohlantiradi. Ekipaj Angra Mainyu ziyoratgohi yashiringan Seedhollowga shoshilib, faqat Avia cherkovi tomonidan hujumga uchragan shaharni topdi. Ular Lilitning elita qo'shinlari orqali jang qilishadi, Idni mag'lub etishadi va Liriyani qutqaradilar. Liriyani qurbon qilish rejalari barbod bo'lgach, Lilit Rolanni qo'lga oladi va uning o'rniga uni qurbonlik sifatida ishlatmoqchi. Keyin u ulkan suzuvchi orolni, Vayoi ustunini chaqiradi va marosimini yakunlash uchun u erga boradi."
                )
        );
        data.add(
                new Data(
                        R.drawable.f,
                        "Destiny 2",
                        "Destiny 2 [b] - bu Bungie tomonidan ishlab chiqilgan bepul onlayn birinchi shaxs otishma video o'yini. U dastlab 2017 yilda PlayStation 4 , Xbox One va Windows uchun o'yin o'ynash uchun to'lov sifatida chiqarilgan. 2019-yil 1-oktabrda “New Light” nomi ostida oʻyinlardan xizmat koʻrsatish modeli sifatida foydalangan holda oʻynash bepul boʻldi,oʻyinkeyingi oy Stadia’da, soʻngra PlayStation 5 va Xbox Series X/S platformalaridaDekabr 2020. Oʻyin Activision tomonidan 2018-yil 31-dekabrgacha, Bungie franshizaga nashr qilish huquqini qoʻlga kiritgunga qadar chop etildi. Bu 2014 yilgi Destiny va uning keyingi kengaytmalarining davomi.\n" +
                                "\n" +
                                "\" Afsonaviy ilmiy fantastika \" dunyosida o'rnatilgan o'yinda rolli o'yinlar elementlari bo'lgan ko'p o'yinchili \"umumiy dunyo\" muhiti mavjud . Asl nusxadagi kabi, Destiny 2 -dagi harakatlar o'yinchiga qarshi muhitga (PvE) va o'yinchiga qarshi o'yinchiga (PvP) o'yin turlariga bo'lingan . Oddiy hikoya missiyalariga qo'shimcha ravishda, PvE uchta o'yinchili \" zarbalar \", zindonlar va olti o'yinchili reydlarni o'z ichiga oladi . Har bir yo'nalish uchun bepul roum-patrul rejimi mavjud bo'lib, unda ommaviy tadbirlar, shuningdek, asl nusxada mavjud bo'lmagan tadbirlar mavjud. Ushbu tadbirlar maqsadli joylarni o'rganishga va o'yinchi bo'lmagan personajlar (NPC) bilan o'zaro ta'sirga qaratilgan ; original Destiny faqat ijtimoiy sohalarda NPClarni ko'rsatdi. PvP ob'ektivga asoslangan rejimlarni, shuningdek, an'anaviy o'lim o'yinlari o'yin usullarini o'z ichiga oladi.\n" +
                                "\n" +
                                "O'yinchilar insoniyatni turli xil begona irqlardan himoya qilish va yaqinlashib kelayotgan zulmat tahdidiga qarshi kurashish uchun Nur deb nomlangan kuchga ega bo'lib, Yerning so'nggi xavfsiz shahri himoyachisi rolini o'z zimmalariga oladilar. Asl Destiny singari , o'yinda hikoyani davom ettiradigan va o'yin bo'ylab yangi tarkibni qo'shadigan kengaytirilgan paketlar mavjud. Taqdirning birinchi yili 2 ikkita kichik kengayishni o'z ichiga oldi, Osirisning la'nati va Warmind . Uchinchi, katta kengaytma, Forsaken , Ikkinchi yilni o'yin jarayonini tubdan ta'mirlash bilan boshladi. Shadowkeep (2019-yil oktabr) navbatdagi kengaytmasining chiqarilishi Uchinchi yil boshlandi. Shadowkeep va kelgusi relizlar o'yinchilardan oldingi premium kontentga ega bo'lishlarini talab qilmaydigan mustaqil versiyalar hisoblanadi. Ushbu to'rtinchi kengayish bilan bir qatorda Destiny 2 ning \"Yangi yorug'lik\" deb nomlangan versiyasi chiqdi , bu Destiny 2 ning bepul o'ynashi mumkin bo'lgan qayta versiyasi bo'lib, u birinchi ikkita kengaytmaga kirishni ham o'z ichiga oladi. Har bir mavsum tarkibi uchun alohida mavsumiy yo'llanmalar ham mavjud bo'ldi. O'shandan beri asosiy Destiny 2 o'yini bepul o'ynagan bo'lsa-da, boshqa barcha tarkiblar sotib olishni talab qiladi.\n" +
                                "\n" +
                                "To'rtinchi yil o'yindagi eng katta ta'mirni ko'rdi, chunki o'yinning dastlabki uch yilidagi mazmunining deyarli yarmi, shu jumladan asl asosiy kampaniya, shuningdek, Osirisning la'nati va Warmind o'yindan olib tashlandi va Bungie Taqdir deb ataydigan narsaga joylashtirildi. Kontent ombori. Ushbu o'zgarish bilan bir qatorda, To'rtinchi yil beshinchi kengayish bilan boshlandi, Beyond Light , bu o'yinchilarga Zulmatning kuchini taqdim etdi. Bungie ushbu kengayishni franchayzing uchun yangi davrning boshlanishi deb ta'riflagan, chunki u 2022-yil boshida Jodugar malikasi va 2023-yil boshida Lightfall tomonidan davom ettiriladi. Shuningdek, Lightfall- ni kuzatib borish uchun \"Yakuniy shakl\" so'nggi bobi ham bo'ladi. Yangi doston boshlanishidan oldin \"Nur va zulmat dostoni\" deb nomlangan taqdirning birinchi dostonini yakunlang .\n" +
                                "\n" +
                                "Chiqarilgandan so'ng, Destiny 2 odatda tanqidchilardan ijobiy sharhlarni oldi. Maqtov uning yaxshilanishiga, xususan, uning dastlabki hikoyasiga, shuningdek, oʻyin oʻyini, vizual tasvirlari, kashfiyot fokuslari, koʻp oʻyinchi va ommaviy holatlarga qaratilgan. Sharhlar qurollarni qayta tasniflash, Leviafan reydi va yangi rejimlar bo'yicha bo'lingan. Destiny 2 The Game Awards 2017 va Game Critics Awards mukofotlari kabi turli mukofotlarga nomzod boʻlgan va gʻolib boʻlgan ."
                )
        );
        data.add(
                new Data(
                        R.drawable.g,
                        "Tekken 8",
                        "Tekken 8 ( yaponcha : yǎng 8 ) - Bandai Namco Studios va Arika tomonidan ishlab chiqilgan jangovar o'yin . Bandai Namco Entertainment oʻyinni PlayStation 5 , Windows va Xbox Series X/S uchun 2024-yil 26-yanvarda chop etdi. Bu kanonning sakkizinchi versiyasi va Tekken seriyasidagi oʻn birinchi umumiy yozuvdir. \"Qorong'u uyg'onadi\" deb nomlangan o'yin hikoyasi rejimi o'zidan oldingi voqealardan olti oy o'tgach sodir bo'ladiva asosiy qahramonlar otasi Kazuya Mishima va o'g'li Jin Kazama o'rtasidagi so'nggi qarama-qarshilikka qaratilgan bo'lib , ikkinchisi birinchisini o'ldirishni xohlaydi. ularning oilaviy nasl-nasabidagi tartibsizlikni tugatish. O'yin hikoyasida 32 ta sobiq va yangi qahramonlar mavjud bo'lib , ularning har biri umumiy hikoyaga hissa qo'shadigan o'z hikoyasiga ega.\n" +
                                "\n" +
                                "Tekken 8- ni ishlab chiqish birinchi marta 2022-yil avgustida Evo 2022- da namoyish etilgan , rasmiy taqdimot keyingi oyda Sony -ning State of Play tadbirida bo‘lib o‘tgan. Ko'proq agressiv ohanglarga e'tibor qaratgan Tekken 8 Unreal Engine 5 yordamida ishlab chiqilgan bo'lib , u o'zidan oldingi versiyasiga qaraganda takomillashtirilgan jangovar elementlar va tizimlarga ega. Tekken 8 shuningdek, \"Issiqlik\" tizimi va \"Tornado\" xitlari kabi yangi mexanikani taqdim etadi. Arcade Quest ularning onlayn rejimiga yana bir qo'shimcha bo'lib, unda turnirlar, arkada xususiyatlari, sozlanishi mumkin bo'lgan avatarlar va o'yin davomida namoyish etiladigan maxsus valyutalar mavjud.\n" +
                                "\n" +
                                "Chiqarilishdan oldin umumiy barqarorlikni ta'minlash uchun o'yin sinovlari 2023 yil iyul va oktyabr oylarida o'tkazildi va demo o'sha yilning dekabr oyida konsollarda taqdim etildi. Yuklab olinadigan tarkib va \u200B\u200Byangi belgilarni o'z ichiga olgan o'yinning birinchi mavsumi o'yiniga oldindan buyurtma berish davrida taqdim etildi. Chiqarilgandan so'ng, Tekken 8 tanqidchilarning e'tirofiga sazovor bo'ldi, ko'plab tanqidchilar o'yinning seriyadagi umumiy rivojlanishini, shuningdek, uning tajovuzkor o'yinini maqtashdi.\n" +
                                "\n" +
                                "O'yin \n" +
                                "Tekken 8 oldingi Tekken o'yinlari bilan bir xil jangovar o'yin formatiga amal qiladi. O'yin prodyuseri Katsuxiro Xarada Tekken 8 o'zidan oldingisiga qaraganda \"tajovuzkorroq\" bo'lishini ta'kidladi, bu tizim himoyalanganlarni emas, balki hujumda faol bo'lgan o'yinchilarni mukofotlashini ko'rsatadi. Bunga erishish uchun o'yin \"Issiqlik\" deb nomlanuvchi yangi tizimni taqdim etdi. Belgilar \"Issiqlik\" holatini qulfdan chiqarganda, ular nafaqat chiplarning shikastlanishiga va qo'shimcha harakatlarning paydo bo'lishiga olib keladi, balki ularning ayrim harakatlarining xususiyatlarini o'zgartiradi, masalan, og'ir qorovul sinishi. Bu jangchilar \"Issiqlik\" holatida ham harakatlarini bekor qilishlari mumkin. Jangchilar harakatlarini ishlatsa, issiqlik taymerini to'xtatish mumkin. [1] Jangchilar oddiy holatning ogʻir hujumi yoki Issiqlik holati belgilaridan himoyalanganda chip zararini ham oladi, bu ularga sogʻligʻini tiklash imkonini beradi . Tekken Tag Tournament o'yinlaridagi faqat teg rejimida sog'liqni saqlash panelini tiklash tizimidan farqli o'laroq , jangchilarning tiklanadigan sog'lig'ini faqat raqibiga hujum qilish orqali tiklash mumkin. [1]\n" +
                                "\n" +
                                "Tekken 8 bir qator texnik yangilanishlar va qayta ishlangan xususiyatlarni o'z ichiga oladi. Oldingi kirishda debyut qilgan \"Rage\" tizimi Tekken 8da yangi o'zgarishlar bilan qaytadi. Misol uchun, \"Rage Drive\" ajratilgan va \"Heat Smash\", \"Issiqlik\" tizimining super harakati sifatida qayta ishlangan. \"Vint\" mexanizmi Tekken 8 dan olib tashlandi va \"Tornado\" kengaytirgich bilan almashtirildi; tizim raqiblarni tezda erga tushganda, erga bog'langan holatda joylashtiradi. O'yinning o'ziga xos bosqichlarida ham xavf mavjud, masalan, devorlari va pollari qattiqroq bo'lib, ular jangchilarning qattiqroq nokaut hujumlari bilan bir necha marta sindirilishi kerak, boshqalari esa devor va polga portlovchi modda urilganda shikastlangan raqiblarning yuqoriga qarab portlashiga olib keladi.\n" +
                                "\n" +
                                "Texnik yaxshilanishlardan tashqari, Tekken 8 boshqa elementlarga o'zgartirishlarni ham o'z ichiga oladi. Haradaning ta'kidlashicha, Tekken 8 ko'proq kinematik jangovar tajriba taqdim etishni maqsad qilgan , bunda asosiy e'tibor sahna vayronalari va o'ziga xos belgilarning ularga bo'lgan munosabatiga qaratilgan. [2] Bundan tashqari, barcha personaj modellari va ovozli aktyorlik avvalgi yozuvlardagi qayta ishlangan kontentdan ko'ra butunlay yangi. Onlayn rejim \"Arcade Quest\" deb nomlangan jangovar lobbini o'z ichiga oladi, unda arkada muhitlari, muntazam onlayn janglar va turnir o'yinlari mavjud. \"Arcade Quest\" foydalanuvchilarga o'z avatarlarini sozlash imkonini beradi va \"Fight Money\" valyutasidan foydalanadi. [3] Tekken 8 yangi avlod Unreal Engine 5 tomonidan quvvatlanadi va bu dvigateldan foydalangan birinchi yirik jangovar o'yin bo'ldi.\n" +
                                "\n" +
                                "Tekken 8 o'zaro o'yin xususiyatlariga ega . [4] PlayStation 5, Windows va Xbox Series X/S oʻyinchilariga franchayzing tarixida birinchi marta bir-biriga qarshi oʻynash imkonini berish. O'yinchining xohishiga ko'ra Cross-Platform Play-ni yoqish yoki o'chirish mumkin. [5]\n" +
                                "\n" +
                                "Tekken 6 -dan stsenariy kampaniyasiga asoslangan Tekken Force Mode faqat asosiy hikoyaning 10-bobida eksklyuzivdir. Bu rejimda issiqlik va g'azab tizimlarining eksklyuziv xususiyatlari mavjud bo'lib, ular asl jangovar stsenariy tizimlarida mavjud bo'lmagan, masalan, Rage Burst va avtomatik ravishda qayta tiklanadigan va to'liq barda qayta foydalanish mumkin bo'lgan issiqlik o'lchagich."
                )
        );
        data.add(
                new Data(
                        R.drawable.h,
                        "Smite",
                        "Smite - bu 2014-yilda bepul o'ynaladigan , uchinchi shaxs uchun mo'ljallangan ko'p o'yinchi onlayn jang maydoni (MOBA) video o'yini Hi-Rez Studios tomonidan Microsoft Windows , Xbox One , PlayStation 4 , Nintendo Switch va Amazon Luna uchun. [7] Smite -daoʻyinchilar xudo, maʼbuda yoki boshqa mifologik figurani boshqaradi va oʻz qobiliyatlari va taktikalarini oʻyinchi tomonidan boshqariladigan boshqa xudolar va oʻyinchi tomonidan boshqarilmaydigan minionlarga qarshi ishlatib, jamoaviy janglarda qatnashadi.\n" +
                                "\n" +
                                "O'yinda bir nechta o'yinchiga qarshi o'yinchi (PVP) rejimlari, ko'plab o'ynaladigan belgilar mavjud va bir nechta turnirlar, jumladan, yillik million dollarlik Smite Jahon chempionati bilan muvaffaqiyatli esport sahnasi mavjud .\n" +
                                "\n" +
                                "O'yin \n" +
                                "Smite juda ko'p turli xil o'yin rejimlariga ega, ularning eng kattasi Conquest. [8] O‘yinchilar Trening (AIga qarshi), Custom, Co-Op (klan/do‘stlar bilan), Oddiy va Reytingli o‘yin uslublaridan birini tanlashi mumkin. U erdan ular turli xil standart o'yin rejimlarini tanlashlari mumkin. Cheksiz oltin kabi noyob qoidalarga ega maxsus tadbirlar o'yinlari ham tez-tez kiritiladi.\n" +
                                "\n" +
                                "Har bir o'yin boshida o'yinchilar o'ynash uchun xudo yoki boshqa mifologik figurani tanlaydilar. 2023-yil dekabr holatiga ko‘ra , o‘yinchilar turli xil panteonlardan , jumladan, Bobil , Keltlar , Xitoy , Misr , Yunon , Hindu , Yapon , Norse , Polineziya , Rim , Mayya , Slavyan , Vudu kabi, lekin ular bilan cheklanmagan holda, turli xil belgilarni tanlashlari mumkin . va Yoruba . Qirol Arturning afsonalari (o'yindagi Artur panteoni deb ataladi) va Cthulhu Mythos (Buyuk Eskilar panteoni deb ataladi) qahramonlari ham ushbu video o'yinda panteonlar hisoblanadi. [9]\n" +
                                "\n" +
                                "Har bir belgi quyidagi sinflardan biri sifatida tasniflanadi: Assassin, Guardian, Hunter, Mage yoki Warrior. Agar boshqacha ko'rsatilmagan bo'lsa, bitta jamoadagi ikkita o'yinchi bir xil belgini tanlay olmaydi (raqobat rejimlarida va qoralama tanlash usulidan foydalanadiganlarda, har bir o'yinchi boshqa belgidan foydalanishi kerak). [9] Muvaffaqiyatli jamoa konfiguratsiyasi odatda xudo tanlashda standart RPG reyd konfiguratsiyasiga (tank, shifobaxsh, jismoniy/sehrli zarar) rioya qilgan holda yaxshi rivojlangan jamoani o'z ichiga oladi.\n" +
                                "\n" +
                                "Aksariyat MOBA o'yinlari yuqoridan pastga qarab o'ynalsa-da , Smite-da o'yinchi xudoni uchinchi shaxs nuqtai nazaridan boshqaradi. Har bir xudo asosiy hujumga, passiv xususiyatga va turli ta'sirlarga ega bo'lgan to'rtta qobiliyatga ega ( hududga zarar etkazish , olomonni boshqarish , holat effektlari va boshqalar). Bu qobiliyatlar o‘yinchining xarakteri o‘ldirilishi , minoralar yoki fenikslarni yiqitish va dushman qahramonlarini mag‘lub etish tajribasiga ega bo‘lish orqali o‘yinchining xarakteri darajasiga ko‘tarilganda olinadi va yaxshilanadi. Maksimal daraja - 20 va har bir keyingi darajaga erishish qiyinroq. Har bir o'yinchi, shuningdek, standart davriy daromad va dushmanlarni o'ldirish (o'yinchi va NPC) orqali oltin to'playdi; oltin ularning xudosi uchun narsalarni sotib olish uchun ishlatiladi, shuningdek, iksirlar, palatalar va qobiliyatlar.\n" +
                                "\n" +
                                "Har bir oʻyin rejimida oʻziga xos xarita mavjud boʻlib, u “boʻlaklarga” boʻlinadi, bu yerda kompyuter tomonidan boshqariladigan minionlar toʻlqinlari dushman bazasiga qarab yuradi va kompyuter tomonidan boshqariladigan yirtqich hayvonlar vaqti-vaqti bilan maʼlum joylarda tarqalib ketadigan “oʻrmon ” . xarita bo'ylab nosimmetrik tarzda. Ushbu o'rmonda yirtqich hayvonlarni o'ldirish tajriba ballari va oltin beradi; Ba'zi yirtqich hayvonlarni o'ldirish \"buff\" ning erga tushishiga olib keladi, u o'yinchi tomonidan ko'tarilganda etkazilgan zarar, harakat tezligi va hujum tezligi kabi statistikaga vaqtinchalik bonuslar beradi. Kamroq paydo bo'ladigan uchta maxsus yirtqich hayvonlar mavjud bo'lib, ular qotillik zarbasini bergan jamoaga ma'lum miqdorda oltin, shuningdek, vaqtinchalik zararni kuchaytiruvchi va bazadan chiqishda tezlikni oshiradi. ["
                )
        );
        data.add(
                new Data(
                        R.drawable.i,
                        "Grand Theft Auto VI",
                        "Grand Theft Auto VI - bu Rockstar Games tomonidan ishlab chiqilayotgan yaqinlashib kelayotgan video o'yin . Bu Grand Theft Auto V (2013) dan keyingi sakkizinchi asosiy Grand Theft Auto o'yiniva umuman olganda o'n oltinchi o'yinbo'lishi kerak . Florida shtatidagi xayoliy ochiq dunyo davlati Leonidava uning Mayami tomonidan ilhomlantirilgan Vitse-Siti ichida o'tadigan voqea Lucia va uning erkak sherigi jinoyatchi dueti haqida bo'lishi kutilmoqda. [a]\n" +
                                "\n" +
                                "Ko'p yillik taxminlar va kutishlardan so'ng, Rockstar 2022 yil fevral oyida o'yin ishlab chiqilayotganligini tasdiqladi. O'sha sentabr oyida tugallanmagan versiyalardan olingan kadrlar internetga tarqalib ketdi, jurnalistlar buni video o'yinlar sanoati tarixidagi eng katta sizdirishdan biri deb ta'rifladilar . O'yin rasman 2023 yil dekabr oyida taqdim etilgan va 2025 yilda PlayStation 5 va Xbox Series X/S uchun chiqarilishi rejalashtirilgan .\n" +
                                "\n" +
                                "Sozlama va belgilar\n" +
                                "Grand Theft Auto VI xayoliy ochiq dunyo davlati Leonidada - Florida shtatida joylashgan bo'lib, u Vitse-Siti o'z ichiga oladi, Mayamining o'ylab topilgan versiyasi . [1] [2] [3] Vitse-Siti avvalroq Grand Theft Auto (1997) filmlarida va Grand Theft Auto: Vice City (2002) va Grand Theft Auto: Vice City Stories (2006) filmlarining asosiy surati sifatida namoyish etilgan . [4] [5] [6] Seriyaning oldingi sarlavhalarida boʻlgani kabi, oʻyin dunyosi zamonaviy Amerika madaniyatini parodiya qiladi, ijtimoiy media va taʼsir qiluvchi madaniyatning satirik tasvirlari hamda Florida odami kabi internet memlariga havolalar . [7] [8] [9] Hikoya jinoiy duetdan iborat: 2000 yildan beri serialning birinchi ayol qahramoni Lusiya [b] va uning erkak sherigi; [a] birinchi treyler Lyusiyani qamoqxonadagi mahbus sifatida tasvirlaydi va keyinchalik sherigi bilan qamoqdan qochib ketadi. [2] [16]\n" +
                                "\n" +
                                "Rivojlanish\n" +
                                "Grand Theft Auto V ning 2013-yilda chiqarilishidan so‘ng , Rockstar North kompaniyasining o‘sha paytdagi prezidenti Lesli Benzis kompaniyada seriyaning keyingi kirishi uchun “ba’zi g‘oyalar” borligini aytdi. [17] 2018-yilda The Know , Project Americas kod nomi bilan atalgan oʻyin asosan Vitse-Siti va qisman Janubiy Amerikada ayol qahramon bilan oʻrnatilishi haqida xabar berdi. [18] 2020-yilda jurnalist Jeyson Shrayer oʻyinning “ilk ishlab chiqilayotgani”ni “oʻrtacha oʻlchamdagi reliz” sifatida maʼlum qildi, bu vaqt oʻtishi bilan oʻzidan oldingi ishlab chiquvchilarning siqilishiga yoʻl qoʻymaslik uchun kengayib boradi . [19] 2021 yilda Tom Xenderson oʻyin xaritasi Fortnite Battle Royale ga oʻxshash rivojlanishi mumkinligini daʼvo qildi . [20] [21] 2022-yilda Shrayer oʻyin 2014-yilda ishlab chiqilganligini va unda Bonni va Klayd tomonidan ilhomlantirilgan ikkita bosh qahramon, jumladan , Latina ayoli ishtirok etishi haqida xabar berdi va ishlab chiquvchilar seriyadagi marginal guruhlar haqida hazillashish tendentsiyasini ehtiyotkorlik bilan buzib tashlashganini daʼvo qildi . [22] [23]\n" +
                                "\n" +
                                "O'yin e'lon qilinishidan bir necha yil oldin kutilgan edi, [24] [25] [26] va jurnalistlarning ta'kidlashicha, ba'zi muxlislar Rockstar Games ning davom etgan sukunatdan hafsalasi pir bo'lgan , ayniqsa Grand Theft Auto V ning qayta chiqarilishini e'lon qilganidan keyin . 2020. [27] [28] [29] Oʻyinga havola qilgan shaxs bir nechta jonli sahna va telekoʻrsatuvlarni toʻxtatgani uchun OAV eʼtiborini tortdi. [30] [31] [32] 2022-yil 4-fevralda Rockstar rivojlanish \"yaxshi davom etayotganini\" tasdiqladi. [33] Iyul oyida Rockstar Red Dead Online ko'proq katta yangilanishlarni olmasligini e'lon qildi, chunki rivojlanish resurslari bo'lajak o'yinga e'tibor qaratish uchun olib tashlangan; [34] sanoat manbalarining taʼkidlashicha, Grand Theft Auto IV (2008) va Red Dead Redemption (2010) rejalashtirilgan remasterlari Grand Theft Auto: The Trilogy – The Definitive Edition (2021) tomonidan qabul qilingan norozilik tufayli toʻxtatilganidan soʻng Rockstar resurslarni qayta taqsimlagan. [35]\n" +
                                "\n" +
                                "2023 yil noyabr oyida Rockstar prezidenti Sem Xauser kompaniyaning 25 yilligini nishonlash uchun dekabr oyi boshida birinchi treyler chiqishini e'lon qildi. [36] [37] Besh soat ichida X (ilgari Twitter) dagi eʼlon oʻyin haqidagi oldingi ikkita postni ortda qoldirib, platformaning oʻyinga oid eng yoqqan postiga aylandi, [38] [39] [40] keyinroq Rockstar’dan oʻzib ketdi. 24 soat ichida 1,8 million layk bosgan treylerning 5-dekabr kuni chiqishini e'lon qilgan post. [41] Boshqa ishlab chiquvchilar oʻzlarining treylerlarini reklama qilish uchun eʼlon formatiga taqlid qilishdi. [42] [43] [15] 4-dekabrda X-da treylerning past sifatli versiyasi sizdirildi; Bunga javoban, Rockstar YouTube- da rasmiy versiyani e'lon qildi, PlayStation 5 va Xbox Series X/S uchun 2025-yilning sarlavhasi, qahramonlari, sozlamalari va chiqarish oynasini ochib berdi . [44] [45] [46]\n" +
                                "\n" +
                                "Treyler 12 soat ichida 46 million, [47] [48] bilan YouTube videosini birinchi kundagi eng koʻp tomosha qilish rekordini yangiladi va 24 soat ichida 93 million koʻrish bilan uchinchi oʻringa chiqdi [49] ] [50] [51] va eng ko'p yoqqan o'yin treyleri 8,9 mln. [52] [53] U Grand Theft Auto V ning 2011-yilda taqdim etilgan treylerini ikki kun ichida 101 million koʻrish bilan umrbod tomoshabinlar sonidan oshib ketdi [54] va yanvar oyiga kelib 168 million tomosha qilingan oʻyin treyleri boʻyicha ikkinchi oʻrinni egalladi. [55] Uning mashhur qoʻshigʻi Tom Pettining \" Love Is a Long Road \" qoʻshigʻi Spotify oqimlari soni qariyb 37.000% oʻsdi , Shazamda deyarli 250.000 ta qidiruvga ega boʻldi va butun dunyo boʻylab iTunes chartida ikkinchi oʻrinni egalladi. [56] Treyler boshqa video o'yinlarda, g'isht plyonkasida va Hyundai World Rally Team tomonidan jonli harakatda muxlislar tomonidan yaratilgan dam olishni tug'dirdi . [57] [58] [59]\n" +
                                "\n" +
                                "2024 yil fevral oyida Shrayer Rockstar xodimlaridan \"hosildorlik va xavfsizlik uchun\" 15 apreldan boshlab uzoqdan ishlashni to'xtatishni va ofislarga to'liq vaqtli qaytishni so'raganini, chunki rivojlanish \"yakuniy bosqichga\" kirishi kerakligi haqida xabar berdi. [60] [61] [62] Buyuk Britaniyaning Mustaqil ishchilar uyushmasi bu qarorni Rockstarning moslashuvchan ish sharoitlarini saqlab qolishlari haqidagi oldingi da'vosiga zid bo'lganligi uchun tanqid qildi, ba'zi anonim xodimlar esa bu xodimlarning sog'lig'i va ma'naviyatiga salbiy ta'sir ko'rsatishi va iste'foga olib kelishi mumkinligidan xavotirda. va siqilish sharoitlari. [62] [63] Mart oyida Kotaku ning Zack Zwiezen bu qaror qisman ichki rejalashtirilgan 2025 yil boshida relizlar oynasida kechikishning oldini olish uchun qilinganligini aytdi; Rivojlanishning \"orqada qolishi\" 2025 yil oxiri yanada amaliyroq ko'rindi, 2026 yilga \"qayta reja\" sifatida kechikish mumkin edi. [64] [65]"
                )
        );
        data.add(
                new Data(
                        R.drawable.j,
                        "Valorant",
                        "Valorant - bu Riot Games tomonidan Windows uchunishlab chiqilgan va nashr etilgan birinchi shaxs taktik qahramon otishmasidir . [3] 2019-yil oktabr oyida Project A kod nomi ostida masxara qilingano‘yin 2020-yil 7-aprelda cheklangan kirish bilan yopiq beta-davrni boshladi, keyin esa 2020-yil 2-iyunda chiqdi. O‘yinni ishlab chiqish 2014-yilda boshlangan. Valorant Counter-Strike seriyasidan ilhom olish, sotib olish menyusi, buzadigan amallar naqshlari va harakat paytida noaniqlik kabi bir nechta mexanikani olish.\n" +
                                "\n" +
                                "O'yin jarayoni\n" +
                                "Valorant - bu yaqin kelajakda o'rnatiladigan jamoaviy birinchi shaxs taktik qahramon otishmasidir . [4] [5] [6] [7] Oʻyinchilar butun dunyo boʻylab bir qancha mamlakatlar va madaniyatlarga asoslangan agentlar, belgilar toʻplamidan biri sifatida oʻynaydilar. [7] Asosiy oʻyin rejimida oʻyinchilar hujum qiluvchi yoki himoyalanuvchi jamoaga tayinlanadi, har bir jamoada besh nafar oʻyinchi boʻladi. Agentlar o'ziga xos qobiliyatlarga ega, ularning har biri to'lovlarni talab qiladi, shuningdek, o'ldirish, o'lim, orblar yoki maqsadlar orqali zaryadlashni talab qiladigan noyob yakuniy qobiliyatga ega. Har bir o'yinchi har bir turni \"klassik\" to'pponcha va bir yoki bir nechta \"imzo qobiliyati\" zaryadlari bilan boshlaydi. [5] Boshqa qurollar va qobiliyatlar uchun toʻlovlarni oʻyin ichidagi iqtisodiy tizim yordamida sotib olish mumkin, bu tizim oldingi tur natijasiga, oʻyinchi javobgar boʻlgan har qanday oʻlimga va bajarilgan maqsadlarga qarab pul mukofotlaydi. O'yinda qurol-yarog'lar assortimenti, shu jumladan ikkilamchi qurollar va avtomatlar , avtomatlar , avtomatlar , avtomatlar va snayper miltiqlari kabi asosiy qurollar mavjud . [8] [9] Avtomatik va yarim avtomatik qurollar mavjud boʻlib , ularning har biri oʻziga xos otishni oʻrganish naqshiga ega boʻlib, aniq oʻq otish uchun oʻyinchi tomonidan boshqarilishi kerak. [9] Hozirda u tanlash uchun 23 ta agentni taklif qiladi. [3] [10] [11] Oʻyinchi oʻz akkauntini yaratgandan soʻng 5 ta qulfdan chiqarilgan agentga ega boʻladi va oʻyin ichidagi valyutani Kingdom Credits toʻplash orqali boshqa agentlarni blokdan chiqarishi kerak boʻladi. Shohlik kreditlarini oʻyin oʻynash yoki kundalik va haftalik vazifalarni bajarish orqali olish mumkin va yangi agentlar yoki kosmetika buyumlarini ochishga sarflash mumkin. Biroq, chiqarilgandan keyingi dastlabki 28 kun ichida yangi Agentlar faqat Valorant Points (VP), Agent ishga qabul qilish tadbirlari yoki bog'langan va faol Xbox Game Pass obunasi bilan qulfdan chiqarilishi mumkin. VP - bu o'yin ichidagi valyuta bo'lib, uni faqat real pulga sotib olish mumkin, [12] [ yaxshiroq manba kerak ] va uni kosmetika buyumlari yoki yangi agentlarga sarflash mumkin.\n" +
                                "\n" +
                                "Baholanmagan\n" +
                                "Reytingsiz standart rejimda o'yin 25 ta eng yaxshisi sifatida o'tkaziladi - 13 raundda birinchi bo'lib g'alaba qozongan jamoa o'yinda g'alaba qozonadi. Hujum qilayotgan jamoada Spike deb nomlangan bomba tipidagi qurilma bor. Ular bir nechta belgilangan joylardan (bomba joylari) birida Spikeni etkazib berishlari va faollashtirishlari kerak. Agar hujum qiluvchi jamoa faollashtirilgan Spikeni 45 soniya davomida muvaffaqiyatli himoya qilsa, u portlab, ma'lum bir hududdagi hamma narsani yo'q qiladi va ular ochko oladilar. [5] Agar himoyachi jamoa shpikni o'chirib qo'yishi mumkin bo'lsa yoki 100 soniyalik raund taymeri hujum qiluvchi jamoa spikni faollashtirmasdan tugasa, himoyachi jamoa ochko oladi. [13] Agar spike faollashgunga qadar jamoaning barcha a'zolari o'chirilgan bo'lsa yoki himoyalangan jamoaning barcha a'zolari spike faollashtirilgandan keyin o'chirilgan bo'lsa, raqib jamoa ochko oladi. [5] Agar ikkala jamoa ham 12 raundda g'alaba qozonsa, to'satdan o'lim ro'y beradi, bunda o'sha raundda g'olib chiqqan jamoa musobaqada g'alaba qozonadi, bu raqobatli o'yinlar uchun qo'shimcha vaqtdan farq qiladi. Bundan tashqari, agar 4 raunddan keyin jamoa o'sha o'yinda mag'lub bo'lishni xohlasa, ular taslim bo'lish uchun ovoz berishni talab qilishlari mumkin. Agar ovoz 4 ga yetsa (raqobatchi uchun 5 dan farqli o'laroq), g'olib jamoa ularni 13 ga etkazish uchun zarur bo'lgan har bir raund uchun barcha g'alaba kreditiga ega bo'ladi, mag'lubiyatga uchragan jamoa esa kreditni yo'qotadi. [14] Jamoa taslim bo'lish uchun faqat uchta imkoniyatga ega bo'ladi: bir marta birinchi bo'limda, bir marta ikkinchi bo'limning to'pponcha raundida va yana bir marta ikkinchi bo'limda.\n" +
                                "\n" +
                                "Spike Rush\n" +
                                "Spike Rush rejimida o'yin 7 raundning eng yaxshisi sifatida o'tkaziladi - 4 raundda birinchi g'alaba qozongan jamoa o'yinda g'alaba qozonadi. O'yinchilar raundni barcha qobiliyatlari to'liq zaryadlangan holda boshlaydilar, ammo standart o'yinlarga qaraganda ikki baravar tez zaryadlanadi. Hujum qilayotgan jamoaning barcha o'yinchilarida boshoq bor, lekin har bir turda faqat bitta shpik faollashtirilishi mumkin. Qurollar har bir turda tasodifiy bo'lib, har bir o'yinchi bir xil quroldan boshlanadi. Standart o'yinda yakuniy nuqta sharlari, shuningdek, bir nechta turli xil quvvat orblari mavjud. [15]\n" +
                                "\n" +
                                "Swiftplay\n" +
                                "Swiftplay o'yinlari - bu Baholanmagan o'yin rejimining qisqartirilgan versiyasi. 10 ta o'yinchi 2 ta jamoaga, hujumchilar va himoyachilarga bo'lingan. Hujumchilar boshoqni ekishlari kerak, himoyachilar esa ularni to'xtatishlari kerak. Swiftplayning reytingsizdan farqi shundaki, eng yaxshisi 9 raund - 5 raundda birinchi g'alaba qozongan jamoa o'yinda g'alaba qozonadi. 4-raundda jamoa o'yinchilari 7-raundda baholanmagan o'yin rejimida bo'lgani kabi almashadilar. O'yinning valyuta tizimi Unrated dan hech qanday o'zgarishlarga ega emas. Swiftplay tezkor o'yin rejimi sifatida mo'ljallangan bo'lib, har bir o'yin uchun o'rtacha 15 daqiqani tashkil etadi, unchalik katta bo'lmagan uchun 40 daqiqadan farqli o'laroq. [16]\n" +
                                "\n" +
                                "Raqobatbardosh\n" +
                                "Raqobatbardosh o'yinlar reytingsiz o'yinlar bilan bir xil bo'lib, 5 o'yin o'ynagandan so'ng har bir o'yinchiga darajani belgilaydigan g'alabaga asoslangan reyting tizimi qo'shiladi. Ushbu rejimni o'ynashdan oldin o'yinchilar 20-darajaga erishishlari kerak. [17] [ yaxshiroq manba kerak ] 2020-yil iyul oyida Riot raqobatbardosh oʻyinlar uchun “ikki farq bilan gʻalaba qozonish” shartini joriy qildi, bunda jamoalar 12-12 da bitta toʻsatdan oʻlim raundini oʻynash oʻrniga, qoʻshimcha vaqtda hujum va himoya raundlarini almashtiradilar. jamoa ikki o'yinda ustunlikni ta'minlab, g'alabaga da'vo qilmaguncha. Har bir qo'shimcha raund o'yinchilarga qurol va qobiliyatlarni sotib olish uchun bir xil miqdordagi pulni, shuningdek, yakuniy qobiliyat to'lovining taxminan yarmini beradi. Ikki raunddan iborat har bir guruhdan so'ng, o'yinchilar o'yinni durang bilan yakunlash uchun ovoz berishlari mumkin, birinchi setdan keyin 6 o'yinchi, ikkinchidan keyin 3 nafar va keyin faqat 1 o'yinchi durangga rozi bo'lishi kerak. Raqobatbardosh reyting tizimi Temirdan Radiantgacha. Radiantdan tashqari har bir daraja 3 ta darajaga ega. [18] [ yaxshiroq manba kerak ] Radiant mintaqaning eng yaxshi 500 nafar oʻyinchisi uchun ajratilgan va Immortal ham, Radiant ham oʻz darajalariga bogʻliq boʻlgan raqamga ega boʻlib, oʻyinchilarga oʻzlarining reytingini boshqalar bilan solishtirishlari mumkin boʻlgan metrikaga ega boʻlish imkonini beradi. ularning darajasi. [19]"
                )
        );
    }
}
